export const FETCH_TUTORIALS = "FETCH_TUTORIALS";
export const FETCH_TUTORIALS_PENDING = "FETCH_TUTORIALS_PENDING";
export const FETCH_TUTORIALS_FULFILLED = "FETCH_TUTORIALS_FULFILLED";
export const FETCH_TUTORIALS_REJECTED = "FETCH_TUTORIALS_REJECTED";

export const INSERT_TUTORIAL = "INSERT_TUTORIAL";
export const INSERT_TUTORIAL_PENDING = "INSERT_TUTORIAL_PENDING";
export const INSERT_TUTORIAL_FULFILLED = "INSERT_TUTORIAL_FULFILLED";
export const INSERT_TUTORIAL_REJECTED = "INSERT_TUTORIAL_REJECTED";

export const UPDATE_TUTORIAL = "UPDATE_TUTORIAL";
export const UPDATE_TUTORIAL_PENDING = "UPDATE_TUTORIAL_PENDING";
export const UPDATE_TUTORIAL_FULFILLED = "UPDATE_TUTORIAL_FULFILLED";
export const UPDATE_TUTORIAL_REJECTED = "UPDATE_TUTORIAL_REJECTED";

export const DELETE_TUTORIAL = "DELETE_TUTORIAL";
export const DELETE_TUTORIAL_PENDING = "DELETE_TUTORIAL_PENDING";
export const DELETE_TUTORIAL_FULFILLED = "DELETE_TUTORIAL_FULFILLED";
export const DELETE_TUTORIAL_REJECTED = "DELETE_TUTORIAL_REJECTED";

export const SET_TUTORIAL = "SET_TUTORIAL";
export const SET_SHOW_ADD_EDIT = "SET_SHOW_ADD_EDIT";


