export const FETCH_TODOS = "FETCH_TODOS";
export const FETCH_TODOS_PENDING = "FETCH_TODOS_PENDING";
export const FETCH_TODOS_FULFILLED = "FETCH_TODOS_FULFILLED";
export const FETCH_TODOS_REJECTED = "FETCH_TODOS_REJECTED";

export const INSERT_TODO = "INSERT_TODO";
export const INSERT_TODO_PENDING = "INSERT_TODO_PENDING";
export const INSERT_TODO_FULFILLED = "INSERT_TODO_FULFILLED";
export const INSERT_TODO_REJECTED = "INSERT_TODO_REJECTED";

export const UPDATE_TODO = "UPDATE_TODO";
export const UPDATE_TODO_PENDING = "UPDATE_TODO_PENDING";
export const UPDATE_TODO_FULFILLED = "UPDATE_TODO_FULFILLED";
export const UPDATE_TODO_REJECTED = "UPDATE_TODO_REJECTED";

export const DELETE_TODO = "DELETE_TODO";
export const DELETE_TODO_PENDING = "DELETE_TODO_PENDING";
export const DELETE_TODO_FULFILLED = "DELETE_TODO_FULFILLED";
export const DELETE_TODO_REJECTED = "DELETE_TODO_REJECTED";

export const SET_TODO = "SET_TODO";
export const SET_SHOW_ADD_EDIT = "SET_SHOW_ADD_EDIT";


